### ISSUE TITLE
Support more command line arguments like -t, -V etc.

### ISSUE THREAD

**Issue by turion** [chisui/nix-mkPandoc#1]
For example, I'd typically run `pandoc` with arguments ` -t revealjs -V theme=serif,revealjs-url=https://github.com/hakimel/reveal.js -i `.

**Comment by chisui** [comment]
These features are already supported. Is should probably provide some more documentation. 

* `-t` is passed using `to` as can be seen [here](https://github.com/chisui/nix-mkPandoc/blob/master/mkPandoc.nix#L10)
* `-V` is expanded to multiple `--variable` args and is passed using the `variables` record as can be seen [here](https://github.com/chisui/nix-mkPandoc/blob/master/mkPandoc.nix#L31).
* Additional parameters can be passed using their full name as arguments directly here [here](https://github.com/chisui/nix-mkPandoc/blob/master/mkPandoc.nix#L34). Their value is ignored.

For your usecase the this should look like this:

```.nix
mkPandoc {
  name        = "...";
  version     = "0.1.0";
  src         = ./simple.md;
  to         = "revealjs";
  variables = {
    theme = "serif";
    reveal-js-url = "https://github.com/hakimel/reveal.js";
  };
  incremental = true;
}
```

Is this sufficient for you?

**Comment by chisui** [comment]
I provided an example file:
https://github.com/chisui/nix-mkPandoc/blob/master/examples/revealjs.nix

**Comment by turion** [comment]
Thanks a lot! I'm trying this right now.
