### ISSUE TITLE
Readme example doesn't work with up-to-date nixpkgs

### ISSUE THREAD

**Issue by turion** [chisui/nix-mkPandoc#2]
Based on your example and the readme, I tried this:

```
{ pkgs ? import <nixpkgs> {} }:
let
  mkPandoc = import (pkgs.fetchFromGitHub {
    owner = "chisui";
    repo = "nix-mkPandoc";
    rev = "e4f47e2ca166a8b103ef50497d937aae819ebe93";
    sha256 = "053jfzqmynlm3rmm73f3aybnlym5c07mpwhn24km5ln373zv9nwv";
  }) {};
in mkPandoc {
  name    = "example.html";
  version = "0.1.0";
  src     = ./example.md;
  to        = "revealjs";
  variables = {
    theme = "serif";
    revealjs-url = "https://github.com/hakimel/reveal.js";
  };
  incremental = true;
  standalone  = true;
}
```
But unfortunately, this gives a very unhelpful error:
```
error: opening file '/nix/store/ndpwizw55zm6xywgj1pgd5y5xs3dhgzf-source/default.nix': No such file or directory
```
When I use your pinned `nixpkgs`, it works, but I have to download a lot of data and populate my store with gigabytes of otherwise unnecessary stuff.

It would be nice to stay in sync with more recent versions of `nixpkgs`. Maybe set up a CI with travis or so? https://docs.travis-ci.com/user/languages/nix I'd be willing to help with that if you want it.

**Comment by chisui** [comment]
I could not reproduce the error with the [setup seen in this gist](https://gist.github.com/chisui/70d68e75f3a1982973d3d9afac7916fb). Could you include the output of the following command:

```sh
nix run nixpkgs.nix-info -c nix-info -m
```

**Comment by turion** [comment]
Weird, I can't reproduce it anymore either. Sorry for the noise.
