### ISSUE TITLE
revealjs CSS is broken

### ISSUE THREAD

**Issue by turion** [chisui/nix-mkPandoc#4]
Revealjs recently moved to SASS (https://github.com/hakimel/reveal.js/issues/191), which broke the CSS paths.

**Comment by turion** [comment]
Sorry, I've been imprecise here. It's not that the move to SASS broke the paths, reveal.js is using SASS since a longer time. But they used to include the precompiled CSS files in the github repo. They don't do that anymore since release 4.0.0

**Comment by chisui** [comment]
I will take a look when I have time. For now you could set the reveal.js url to an older version.

**Comment by turion** [comment]
I've tried to work around it by setting:

```nix
    revealjs-url = "https://raw.githubusercontent.com/hakimel/reveal.js/3.9.2";
```

So the whole example (https://github.com/chisui/nix-mkPandoc/blob/e4f47e2ca166a8b103ef50497d937aae819ebe93/examples/revealjs.nix) now reads:

```nix
{ pkgs     ? import ./nixpkgs.pinned.nix
, mkPandoc ? import ../default.nix { inherit pkgs; }
}:
mkPandoc {
  name      = "revealjs.html";
  version   = "0.1.0";
  src       = ./revealjs.md;
  to        = "revealjs";
  variables = {
    theme = "serif";
    revealjs-url = "https://raw.githubusercontent.com/hakimel/reveal.js/3.9.2";
  };
  incremental = true;
  standalone  = true;
}
```

This causes the CSS and JS links in the generated HTML to be correct as far as I can see, but still the example doesn't work.

**Comment by chisui** [comment]
It's using the default pandoc revealjs template. Have you tried the example with a newer nixpgs version?

**Comment by turion** [comment]
Ah, this is because the MIME type of files served raw is `text/plain`. This works:

```
    revealjs-url = pkgs.fetchFromGitHub {
      owner = "hakimel";
      repo = "reveal.js";
      rev = "3.9.2";
      sha256 = "1xaqgrib3m8ijnphph3aiz6d98w2mm1hlz643dargd12h4kx1lll";
    };
```

**Comment by turion** [comment]
> Have you tried the example with a newer nixpgs version?

With my snippet it works both in your example and my presentation.

**Comment by chisui** [comment]
That's a more nix way to do it. I'll change the example. Unfortunately this makes the result not portable anymore as far as I can tell.

**Comment by turion** [comment]
Not portable in the sense that it now refers to store paths? Yes, that's true, unfortunately. Maybe there is a better way to download older releases. Current pandoc documentation recommends something like:

https://unpkg.com/reveal.js@3.9.2/

(See https://pandoc.org/MANUAL.html#variables-for-html-slides)

 Or better even, find a way to build with an up-to-date reveal.js. I'm not sure 

(EDIT: Fix unpkg link)

**Comment by turion** [comment]
It works with this:

```
    revealjs-url = "https://unpkg.com/reveal.js@3.9.2";
```

And as far as I can see, there is no reference to the nix store then.

**Comment by turion** [comment]
My vague guess is that it should be possible to make it work with version 4 of reveal.js, if an up-to-date pandoc is used, since the pandoc docs refer to version 4.

**Comment by chisui** [comment]
I just searched the manual for a concrete reveal.js version and couldn't find one. Could you show me where you found it? `nixpkgs-unstable` includes [`pandoc 2.14.0.3`](https://pandoc.org/releases.html#pandoc-2.14.0.3-2021-06-22). I couldn't find anything about a version change in the releasenotes of newer versions.

For now I'll just use the 3.9.2 url in the example.

**Comment by chisui** [comment]
It seems that pandoc 2.14.0.3 already expects reveal.js 4. The URLs all include the `dist/` path segment, which is only present in 4+. I updated the example using the npm tarball. This works for me locally. Unfortunately this creates a result that points into the nix store. I'll take a look if there is a way to embed the resources directly inside the output html.

**Comment by chisui** [comment]
Simple: use `self-contained`. I added it to the example.

**Comment by turion** [comment]
Fantastic, can confirm that this works!

> I just searched the manual for a concrete reveal.js version and couldn't find one. Could you show me where you found it? 

Yes, it's in https://pandoc.org/MANUAL.html#variables-for-html-slides, where it says:

> revealjs-url
    base URL for reveal.js documents (defaults to https://unpkg.com/reveal.js@^4/) 

So it's the newest version 4.
